/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdjacentRouteImport } from './routes/adjacent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnimatedFilmsRouteImport } from './routes/animated-films'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as LiveActionRouteImport } from './routes/live-action'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WebOfLifeRouteImport } from './routes/web-of-life'
import { Route as WhatIsTheSpiderVerseRouteImport } from './routes/what-is-the-spider-verse'
import { Route as DirectoryIndexRouteImport } from './routes/directory.index'
import { Route as DirectoryCharacterIdRouteImport } from './routes/directory.$characterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjacentRoute = AdjacentRouteImport.update({
  id: '/adjacent',
  path: '/adjacent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimatedFilmsRoute = AnimatedFilmsRouteImport.update({
  id: '/animated-films',
  path: '/animated-films',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveActionRoute = LiveActionRouteImport.update({
  id: '/live-action',
  path: '/live-action',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WebOfLifeRoute = WebOfLifeRouteImport.update({
  id: '/web-of-life',
  path: '/web-of-life',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsTheSpiderVerseRoute = WhatIsTheSpiderVerseRouteImport.update({
  id: '/what-is-the-spider-verse',
  path: '/what-is-the-spider-verse',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryCharacterIdRoute = DirectoryCharacterIdRouteImport.update({
  id: '/directory/$characterId',
  path: '/directory/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adjacent': typeof AdjacentRoute
  '/admin': typeof AdminRoute
  '/animated-films': typeof AnimatedFilmsRoute
  '/collection': typeof CollectionRoute
  '/live-action': typeof LiveActionRoute
  '/timeline': typeof TimelineRoute
  '/web-of-life': typeof WebOfLifeRoute
  '/what-is-the-spider-verse': typeof WhatIsTheSpiderVerseRoute
  '/directory/$characterId': typeof DirectoryCharacterIdRoute
  '/directory/': typeof DirectoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adjacent': typeof AdjacentRoute
  '/admin': typeof AdminRoute
  '/animated-films': typeof AnimatedFilmsRoute
  '/collection': typeof CollectionRoute
  '/live-action': typeof LiveActionRoute
  '/timeline': typeof TimelineRoute
  '/web-of-life': typeof WebOfLifeRoute
  '/what-is-the-spider-verse': typeof WhatIsTheSpiderVerseRoute
  '/directory/$characterId': typeof DirectoryCharacterIdRoute
  '/directory': typeof DirectoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adjacent': typeof AdjacentRoute
  '/admin': typeof AdminRoute
  '/animated-films': typeof AnimatedFilmsRoute
  '/collection': typeof CollectionRoute
  '/live-action': typeof LiveActionRoute
  '/timeline': typeof TimelineRoute
  '/web-of-life': typeof WebOfLifeRoute
  '/what-is-the-spider-verse': typeof WhatIsTheSpiderVerseRoute
  '/directory/$characterId': typeof DirectoryCharacterIdRoute
  '/directory/': typeof DirectoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adjacent'
    | '/admin'
    | '/animated-films'
    | '/collection'
    | '/live-action'
    | '/timeline'
    | '/web-of-life'
    | '/what-is-the-spider-verse'
    | '/directory/$characterId'
    | '/directory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adjacent'
    | '/admin'
    | '/animated-films'
    | '/collection'
    | '/live-action'
    | '/timeline'
    | '/web-of-life'
    | '/what-is-the-spider-verse'
    | '/directory/$characterId'
    | '/directory'
  id:
    | '__root__'
    | '/'
    | '/adjacent'
    | '/admin'
    | '/animated-films'
    | '/collection'
    | '/live-action'
    | '/timeline'
    | '/web-of-life'
    | '/what-is-the-spider-verse'
    | '/directory/$characterId'
    | '/directory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdjacentRoute: typeof AdjacentRoute
  AdminRoute: typeof AdminRoute
  AnimatedFilmsRoute: typeof AnimatedFilmsRoute
  CollectionRoute: typeof CollectionRoute
  LiveActionRoute: typeof LiveActionRoute
  TimelineRoute: typeof TimelineRoute
  WebOfLifeRoute: typeof WebOfLifeRoute
  WhatIsTheSpiderVerseRoute: typeof WhatIsTheSpiderVerseRoute
  DirectoryCharacterIdRoute: typeof DirectoryCharacterIdRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjacent': {
      id: '/adjacent'
      path: '/adjacent'
      fullPath: '/adjacent'
      preLoaderRoute: typeof AdjacentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animated-films': {
      id: '/animated-films'
      path: '/animated-films'
      fullPath: '/animated-films'
      preLoaderRoute: typeof AnimatedFilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-action': {
      id: '/live-action'
      path: '/live-action'
      fullPath: '/live-action'
      preLoaderRoute: typeof LiveActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-of-life': {
      id: '/web-of-life'
      path: '/web-of-life'
      fullPath: '/web-of-life'
      preLoaderRoute: typeof WebOfLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-the-spider-verse': {
      id: '/what-is-the-spider-verse'
      path: '/what-is-the-spider-verse'
      fullPath: '/what-is-the-spider-verse'
      preLoaderRoute: typeof WhatIsTheSpiderVerseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$characterId': {
      id: '/directory/$characterId'
      path: '/directory/$characterId'
      fullPath: '/directory/$characterId'
      preLoaderRoute: typeof DirectoryCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdjacentRoute: AdjacentRoute,
  AdminRoute: AdminRoute,
  AnimatedFilmsRoute: AnimatedFilmsRoute,
  CollectionRoute: CollectionRoute,
  LiveActionRoute: LiveActionRoute,
  TimelineRoute: TimelineRoute,
  WebOfLifeRoute: WebOfLifeRoute,
  WhatIsTheSpiderVerseRoute: WhatIsTheSpiderVerseRoute,
  DirectoryCharacterIdRoute: DirectoryCharacterIdRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
