const fs = require('fs');
const path = require('path');

const docsDir = path.join(__dirname, '..', 'docs');

const files = {
  'README.md': `# The Amazing Web Docs\n\nWelcome to the official documentation for The Amazing Web, a highly interactive 3D timeline and directory mapping the entire Spider-Verse.\n\nThis project bridges the gap between various Spider-Man continuities, including live-action films, animated series, and comic book runs, presenting them in a unified, visually striking 3D multiverse graph. \n\n## Repository Structure\n- **Frontend/**: A Vite + React application powered by TanStack Router and Three.js.\n- **src/**: An Express.js backend providing RESTful API endpoints.\n- **prisma/**: Database schema and migrations for PostgreSQL.\n- **scripts/**: Utility scripts for data seeding, scraping, and maintenance.\n\nFor detailed information, please explore the specific sections within the \`docs/\` directory.`,

  '01-overview/project-overview.md': `# Project Overview\n\n## What is The Amazing Web?\nThe Amazing Web is an interactive 3D timeline and directory mapping the entire Spider-Verse. It tracks the various continuities, alternate Earths, crossover events, characters, and live-action movies across the Marvel Multiverse.\n\n## Core Features\n- **3D Multiverse Graph**: A WebGL-powered 3D timeline rendering thousands of nodes (characters, events) across branching Earth timelines.\n- **Content Directory**: A searchable, filterable directory of every Spider-variant.\n- **Admin Controls**: Secure, authenticated content management tools built directly into the UI.\n- **Dynamic Image Hosting**: Direct integration with Supabase Storage for character profile pictures and event images.\n\n## Target Audience\n- Marvel fans and researchers looking to understand the complex web of Spider-Man continuities.\n- Developers interested in WebGL, React-Three-Fiber, and full-stack TypeScript applications.`,
  
  '01-overview/problem-statement.md': `# Problem Statement\n\nNavigating the complex, branching continuity of the Spider-Verse across comics, animated films, and live-action media is difficult for fans. There is no unified, visual database to explore these connections.\n\nTraditional wikis present information in dense text formats with hyperlinks, which fails to convey the *chronological and dimensional relationships* between characters (e.g., how Miles Morales crossing over to Earth-616 affects the timeline).\n\nThe Amazing Web solves this by spatializing the data: turning timelines into physical branches in a 3D space.`,
  
  '01-overview/objectives.md': `# Objectives\n\n1. **Data Visualization**: Provide a visually stunning, performant 3D timeline of the Spider-Verse capable of rendering hundreds of nodes simultaneously without frame drops.\n2. **Comprehensive Database**: Offer a robust relational directory of Spider-variants, Earths, and Events.\n3. **Content Management**: Allow secure, authenticated administration of data through an integrated editing interface (no external CMS required).\n4. **Seamless Deployment**: Maintain a decoupled architecture allowing independent scaling of the static frontend and the API backend.`,

  '02-architecture/system-architecture.md': `# System Architecture\n\nThe Amazing Web utilizes a decoupled, modern full-stack architecture.\n\n## Frontend (Vercel)\n- **Framework**: React 18, Vite\n- **Routing**: TanStack Router (File-based routing)\n- **3D Engine**: \`react-force-graph-3d\` (Three.js wrapper)\n- **Styling**: Tailwind CSS\n- **State Management**: TanStack Query (React Query) for server state.\n\n## Backend (Render)\n- **Runtime**: Node.js\n- **Framework**: Express.js\n- **ORM**: Prisma\n- **File Handling**: Multer (in-memory buffer parsing)\n\n## Database & Storage (Supabase)\n- **Database**: PostgreSQL with Connection Pooling (PgBouncer) on port 6543.\n- **Storage**: Supabase Object Storage ('images' bucket).\n\n\`\`\`mermaid\nflowchart TD\n    Client[Web Browser] -->|HTTP Requests| Vercel[Vercel - Static Frontend]\n    Client -->|API Requests| Render[Render - Express Backend]\n    Render -->|Prisma TCP 6543| SupabaseDB[(Supabase PostgreSQL)]\n    Render -->|HTTPS API| SupabaseStorage[Supabase Object Storage]\n\`\`\``,
  
  '02-architecture/data-flow.md': `# Data Flow\n\n## Image Upload Sequence\nWhen an administrator uploads a new image for a character or event, the following flow occurs entirely in memory to optimize speed and security:\n\n\`\`\`mermaid\nsequenceDiagram\n    participant Admin as Admin Client\n    participant Backend as Express API\n    participant Storage as Supabase Storage\n    \n    Admin->>Backend: POST /api/upload (multipart/form-data)\n    Note over Admin,Backend: Includes x-api-key header\n    Backend->>Backend: Verify API Key\n    Backend->>Backend: Multer parses file to memory buffer\n    Backend->>Storage: upload(buffer, { contentType })\n    Storage-->>Backend: Upload Success\n    Backend->>Storage: getPublicUrl()\n    Storage-->>Backend: Public URL String\n    Backend-->>Admin: 200 OK { url: "https://..." }\n\`\`\``,

  '03-installation/prerequisites.md': `# Prerequisites\n\nTo run this project locally, ensure you have the following installed:\n\n- **Node.js**: v18.0.0 or higher.\n- **npm**: v9.0.0 or higher.\n- **Git**: For version control.\n- **PostgreSQL Database**: A Supabase project is highly recommended for full compatibility with the Storage API.\n- **TypeScript**: Globally installed (optional, but recommended).`,
  
  '03-installation/installation.md': `# Installation & Setup\n\n### 1. Clone the Repository\n\`\`\`bash\ngit clone https://github.com/thamizhans/theamazingweb.git\ncd theamazingweb\n\`\`\`\n\n### 2. Install Backend Dependencies\n\`\`\`bash\nnpm install\n\`\`\`\n\n### 3. Install Frontend Dependencies\n\`\`\`bash\ncd Frontend\nnpm install\ncd ..\n\`\`\`\n\n### 4. Environment Variables\nCreate a \`.env\` file in the root directory:\n\`\`\`env\nDATABASE_URL="postgresql://postgres.[ID]:[PASSWORD]@aws-0-[REGION].pooler.supabase.com:6543/postgres?pgbouncer=true"\nSUPABASE_URL="https://[ID].supabase.co"\nSUPABASE_SERVICE_ROLE_KEY="your-service-role-key"\nAPI_SECRET_KEY="your-secure-password"\nPORT=3001\n\`\`\`\n\n### 5. Generate Prisma Client\n\`\`\`bash\nnpx prisma generate\n\`\`\`\n\n### 6. Start the Development Servers\nOpen two terminal windows.\n\n**Terminal 1 (Backend):**\n\`\`\`bash\nnpm start\n\`\`\`\n\n**Terminal 2 (Frontend):**\n\`\`\`bash\ncd Frontend\nnpm run dev\n\`\`\``,

  '04-usage/user-guide.md': `# User Guide\n\n## Exploring the 3D Timeline\n- **Navigation**: Click and drag to rotate the 3D space. Scroll the mouse wheel to zoom in and out.\n- **Nodes**: Hover over any glowing node to see details about the character or event. Click a node to open its full profile.\n- **Branches**: Each colored line represents a different Earth/Universe. \n\n## Using the Directory\n- Click the **Directory** button in the top navigation.\n- Use the filter chips at the top to filter characters by **Earth**, **Medium** (Comics, Animated, Live-Action), or **Tags**.\n- Use the search bar to find characters by name or alias.\n\n## Admin Controls\nIf you have the Admin API key configured in your \`localStorage\`:\n- Edit buttons will appear on all character and event cards.\n- A floating "Add Character" button will be visible in the Directory.\n- You can upload images directly from your computer; they will be hosted on Supabase automatically.`,

  '05-technical/frontend.md': `# Frontend Technical Details\n\n## Framework\nThe frontend is built using **Vite**, offering lightning-fast HMR and optimized production builds. It uses **React 18** with strict mode enabled.\n\n## Routing\n**TanStack Router** is used for type-safe, file-based routing. Routes are defined in \`Frontend/src/routes/\` and generated automatically via the TanStack Vite plugin.\n\n## 3D Rendering\nThe \`react-force-graph-3d\` library handles the 3D visualization. It wraps Three.js and provides a force-directed graph physics engine.\n- **Optimization**: The graph limits device pixel ratio (\`dpr\`) to a maximum of 2 to prevent WebGL crashes on mobile devices.\n- **Layout**: The sticky hero container uses \`h-[100dvh]\` to ensure the canvas does not jitter when mobile browser address bars expand/collapse.\n\n## Styling\n**Tailwind CSS** handles all styling, utilizing a custom design system defined in \`tailwind.config.ts\`. The theme relies heavily on CSS variables for dynamic dark mode (Void theme).`,
  
  '05-technical/backend.md': `# Backend Technical Details\n\n## API Framework\nThe backend is a robust **Express.js** application written in TypeScript. It operates as a RESTful API serving JSON data to the frontend.\n\n## Data Access Layer\n**Prisma ORM** provides type-safe database queries. The schema is located in \`prisma/schema.prisma\`. Prisma handles connection pooling natively, but is configured to connect to Supabase's IPv4 PgBouncer port (6543) for serverless compatibility.\n\n## File Processing\n**Multer** is used as middleware for the \`/api/upload\` route. Instead of saving files to the local disk, Multer is configured with \`multer.memoryStorage()\`. The resulting buffer is passed directly to the Supabase Storage SDK, ensuring the server remains stateless.`,
  
  '05-technical/database.md': `# Database Schema\n\nThe PostgreSQL database consists of four primary models:\n\n## Earth\nRepresents a specific universe in the multiverse.\n- \`id\`: Primary Key (e.g., "earth-616")\n- \`designation\`: Human-readable name (e.g., "Earth-616")\n- \`hex\`: Color code used for rendering the branch in the 3D graph.\n\n## Character\nRepresents a Spider-variant, ally, or villain.\n- \`id\`: Primary Key\n- \`alias\`: Superhero name (e.g., "Spider-Man")\n- \`name\`: Secret identity\n- \`earthId\`: Foreign Key linking to Earth\n\n## TimelineEvent\nRepresents a significant comic run, movie, or crossover event.\n- \`id\`: Primary Key\n- \`title\`: Event title\n- \`year\`: Chronological sorting value\n- \`participants\`: Array of Character IDs involved in the event.\n\n## Movie\nSpecifically tracks live-action films.\n- \`id\`: Primary Key\n- \`title\`: Movie title\n- \`releaseDate\`: Theatrical release date`,

  '06-security/security-model.md': `# Security Model\n\nThe application employs a flat, role-based security model. Users are classified as either Anonymous (Read-Only) or Admin (Read-Write).\n\n## Authentication Flow\n1. The admin user inputs the secret key into the Frontend UI (Command Palette or Admin Gate).\n2. The key is stored in the browser's \`localStorage\` as \`spider-admin-key\`.\n3. The Frontend appends this key to the \`x-api-key\` header on all POST, PUT, and DELETE requests.\n4. The Backend \`authMiddleware\` intercepts the request.\n5. If \`req.headers['x-api-key'] === process.env.API_SECRET_KEY\`, the request proceeds.\n6. Otherwise, a \`401 Unauthorized\` response is returned.`,
  
  '06-security/threat-model.md': `# Threat Model\n\n| Asset | Threat | Attack Vector | Impact | Existing Mitigation | Residual Risk |\n|------|--------|---------------|--------|--------------------|---------------|\n| Database Records | Unauthorized Modification | Direct API calls to mutation endpoints | High | \`x-api-key\` validation via \`authMiddleware\` | Low (Requires key compromise) |\n| Supabase Storage | Unrestricted Uploads | Flooding the \`/api/upload\` endpoint | Medium | Endpoint is protected by \`authMiddleware\` | Low |\n| .env Secrets | Credential Leakage | Committing \`.env\` to version control | Critical | Ignored via \`.gitignore\` | None |\n| API Availability | DDoS Attacks | Spamming GET requests | Medium | None currently | Medium |`,

  '08-api-reference/endpoints.md': `# API Endpoints Reference\n\n## GET Endpoints (Public)\n- \`GET /api/characters\`: Returns all characters.\n- \`GET /api/characters/:id\`: Returns a specific character.\n- \`GET /api/earths\`: Returns all Earths.\n- \`GET /api/events\`: Returns all timeline events.\n- \`GET /api/movies\`: Returns all movies.\n\n## POST Endpoints (Protected)\n- \`POST /api/characters\`: Create a character. Requires \`x-api-key\`.\n- \`POST /api/earths\`: Create an Earth. Requires \`x-api-key\`.\n- \`POST /api/upload\`: Upload an image file (multipart/form-data). Requires \`x-api-key\`.\n\n## PUT/DELETE Endpoints (Protected)\n- \`PUT /api/characters/:id\`: Update a character. Requires \`x-api-key\`.\n- \`DELETE /api/characters/:id\`: Delete a character. Requires \`x-api-key\`.`,
  
  '08-api-reference/authentication.md': `# Authentication Implementation\n\nAll protected endpoints must include the \`x-api-key\` header.\n\n### Example Request (cURL)\n\`\`\`bash\ncurl -X POST http://localhost:3001/api/characters \\\n  -H "Content-Type: application/json" \\\n  -H "x-api-key: spider-admin-123" \\\n  -d '{"id": "new-spidey", "alias": "Spider-Man"}'\n\`\`\`\n\n### Backend Middleware Source\n\`\`\`typescript\nimport { Request, Response, NextFunction } from 'express';\n\nexport const authMiddleware = (req: Request, res: Response, next: NextFunction) => {\n  const apiKey = req.headers['x-api-key'];\n  const validKey = process.env.API_SECRET_KEY;\n\n  if (!apiKey || apiKey !== validKey) {\n    return res.status(401).json({ error: 'Unauthorized: Invalid API Key' });\n  }\n\n  next();\n};\n\`\`\``,

  '09-deployment/deployment.md': `# Deployment Architecture\n\nThe Amazing Web uses a decoupled deployment strategy to maximize edge caching for the frontend while maintaining a persistent connection pool for the backend.\n\n## Frontend (Vercel)\n- Deployed automatically via GitHub integration.\n- Root Directory: \`Frontend\`\n- Build Command: \`npm run build\`\n- Install Command: \`npm install\`\n- Env Var: \`VITE_API_URL = https://the-amazing-web-api.onrender.com/api\`\n\n## Backend (Render)\n- Deployed via Web Service.\n- Root Directory: \`.\` (Repository Root)\n- Build Command: \`npm install\`\n- Start Command: \`npm start\`\n- Contains a \`postinstall\` script (\`npx prisma generate\`) to ensure the Prisma client is built during the deployment phase.`,
  
  '09-deployment/production.md': `# Production Database Configuration\n\nWhen deploying to Render, the application communicates with Supabase PostgreSQL.\n\n### IPv4 Transaction Pooler\nBecause Render operates in an IPv4 environment, it cannot connect directly to Supabase's IPv6 direct connection string. \n\n**CRITICAL FIX**: The \`DATABASE_URL\` environment variable on Render MUST use the Supabase Transaction Pooler URL.\n- Port: \`6543\`\n- Suffix: \`?pgbouncer=true\`\n- Example: \`postgresql://postgres.xxx:[PASSWORD]@aws-0-ap.pooler.supabase.com:6543/postgres?pgbouncer=true\``,

  '11-reference/changelog.md': `# Changelog\n\n## v1.0.1 (Current)\n- Fixed mobile viewport issues (\`100dvh\`) for sticky hero canvases on iOS Safari.\n- Fixed hardcoded \`localhost:3001\` API fetches that caused 404 errors in production.\n- Migrated database schema to PostgreSQL (Supabase).\n- Decoupled frontend (Vercel) and backend (Render) architectures.\n\n## v1.0.0\n- Initial Proof of Concept.\n- SQLite local database.\n- 3D Multiverse stage built using \`react-force-graph-3d\`.\n- Basic CRUD via Admin panel.`,
  
  '11-reference/known-issues.md': `# Known Limitations & Issues\n\n### Testing\n- **No Automated Tests:** The test suite is currently empty and relies on manual validation. Jest and React Testing Library should be implemented.\n\n### Media Handling\n- **No Image Resizing:** The \`/api/upload\` route streams the raw image buffer directly to Supabase. Large files (e.g., 5MB JPEGs) are not compressed, which can hurt frontend performance on mobile networks. \n- *Suggested Fix:* Implement \`sharp.js\` in the Multer middleware to resize images to WebP formats before uploading to Supabase.\n\n### Security\n- **Static API Key:** The system uses a single master key instead of per-user JWTs, making revocation difficult.`
};

Object.entries(files).forEach(([filePath, content]) => {
  const fullPath = path.join(docsDir, filePath);
  const dirName = path.dirname(fullPath);
  
  if (!fs.existsSync(dirName)) {
    fs.mkdirSync(dirName, { recursive: true });
  }
  
  fs.writeFileSync(fullPath, content);
});

console.log('Documentation expanded and updated successfully!');
